### ISSUE TITLE
SSH connection issue

### ISSUE THREAD

**Issue by deepktp** [devlinx9/muon-ssh#112]
**Describe the bug**
I have created an VPS recently on Digital Ocean using PRIVATE key and passphrase.
But Muon unable to connect with it. I have some other VPS created with same method, but they work fine.
Only new thing is i have added only special characters for VPS passphrase maybe this is the issue (Not Sure).
My passphrase is *(^%#^&&&#@!@
also i am able to connect with VPS using Putty so my passphrase and private key is correct.

**To Reproduce**
1. Create digital Ocean droplet (VPS) with private key generated with PuttyKeyGen
1. Use special characters only passphrase
**Expected behavior**
Should be able to connect with VPS.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 2404
 - Muon Version 2.2.0

Some logs from terminal 

`
Terminal ancestor component shown
Terminal component shown
Making visible...
Trying to get allowed authentication methods...
List of allowed authentications: [publickey]
Trying auth method: publickey
Key provider: net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile@201190fd
Key type: unknown
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:342)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:360)
        at muon.app.ssh.SshClient2.authPublicKey(SshClient2.java:118)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:242)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
        at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
        at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:383)
        at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile@201190fd
        at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:47)
        at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62)
        at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81)
        at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
        at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:73)
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:221)
        ... 8 more
Caused by: java.io.IOException: Invalid passphrase
        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.verify(PuTTYKeyFile.java:318)
        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.parseKeyPair(PuTTYKeyFile.java:240)
        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.readKeyPair(PuTTYKeyFile.java:114)
        at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
        at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:45)
        ... 13 more
java.io.IOException: Authentication failed
        at muon.app.ssh.SshClient2.connect(SshClient2.java:279)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
        at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
        at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:383)
        at java.base/java.lang.Thread.run(Thread.java:842)
Terminal wrapper disconnecting
currentSession: muon.app.ui.components.session.terminal.CustomJediterm[,0,0,989x491,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@74542f71,flags=9,maximumSize=,minimumSize=,preferredSize=]
Disconnected
`

**Comment by deepktp** [comment]
It looks like putty keys are not supported so i changed them and now it works fine. But there was information about this issue
