### ISSUE TITLE
Can't connect to MiSTer

### ISSUE THREAD

**Issue by chris-y** [devlinx9/muon-ssh#56]
**Describe the bug**
I can connect to everything except my MiSTer.  It just runs a custom version of Linux, username root.  SSH from terminal on the same machine is working fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a connection to the MiSTer, root/password
2. Click on Connect
3. Banner shows "Session not connected"

**Expected behavior**
A connection and terminal prompt.

**Screenshots**
Muon:
![image](https://user-images.githubusercontent.com/1818803/146674360-08caba9f-1287-4803-9e72-b14a6abaff22.png)

SSH:
![image](https://user-images.githubusercontent.com/1818803/146674403-f7b63491-46d6-4253-a96b-fa0d9d107d6b.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS 64-bit Bullseye
 - Muon Version 2.1.0

**Additional context**
This was previously working on Snowflake.

**Comment by chris-y** [comment]
I just clicked on the File Browser tab and that section is working - so it's just the terminal which is not connecting!

**Comment by devlinx9** [comment]
Can you please start muonssh from terminal and send me the logs when you try to connect?

**Comment by chris-y** [comment]
```
Making visible...
called for index: 0 0 0false
Terminal ancestor component shown
Terminal component shown
Trying to get allowed authentication methods...
List of allowed authentications: [publickey, password, keyboard-interactive]
Trying auth method: publickey
java.lang.Exception: No suitable key providers
	at muon.app.ssh.SshClient2.authPublicKey(SshClient2.java:115)
	at muon.app.ssh.SshClient2.connect(SshClient2.java:243)
	at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
	at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:386)
	at java.base/java.lang.Thread.run(Thread.java:829)
Trying auth method: password
net.schmizz.sshj.connection.ConnectionException: Request failed
	at net.schmizz.sshj.connection.channel.AbstractChannel.gotResponse(AbstractChannel.java:405)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:192)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:515)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Terminal wrapper disconnecting
currentSession: muon.app.ui.components.session.terminal.CustomJediterm[,0,0,1821x969,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@6ac650e,flags=9,maximumSize=,minimumSize=,preferredSize=]
Disconnected
Exec pty resized:- col: 226 row: 48 wp: 1812 hp: 912

```

**Comment by devlinx9** [comment]
The Muon log doesn't tell what's wrong. Can try again and send me the logs from the server when the connection fails?, perhaps we could see more info from the server side...

**Comment by chris-y** [comment]
It looks like this is what I'm getting from the server:
```
Accepted password for root from 192.168.0.84 port 34916 ssh2
Received disconnect from 192.168.0.84 port 34916:11: 
Disconnected from user root 192.168.0.84 port 34916
```

Appears to be accepting the password and then Muon is disconnecting for some reason?

**Comment by diamkil** [comment]
getting the same error in my console and the same bug

**Comment by devlinx9** [comment]
Finally, I know what's the issue, you can download the beta version for testing

**Comment by devlinx9** [comment]
The error is resolved in version 2.2.0
