### ISSUE TITLE
NullPointerExecption in PasswordFinderDialog when private key requires a password

### ISSUE THREAD

**Issue by mgmgwi** [devlinx9/muon-ssh#63]
**Describe the bug**
I'm trying to authenticate with a private key which requires a password. There is no password dialog and I get an red error "Session not connected". The log has this 

```
List of allowed authentications: [publickey]
Trying auth method: publickey
Key provider: com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile@1f16516b
java.lang.NullPointerException
	at muon.app.ssh.PasswordFinderDialog.reqPassword(PasswordFinderDialog.java:37)
	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.initializeCipher(OpenSSHKeyV1KeyFile.java:143)
	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.decryptBuffer(OpenSSHKeyV1KeyFile.java:132)
	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readDecodedKeyPair(OpenSSHKeyV1KeyFile.java:118)
	at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:85)
	at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
	at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getType(BaseFileKeyProvider.java:87)
	at muon.app.ssh.SshClient2.authPublicKey(SshClient2.java:105)
	at muon.app.ssh.SshClient2.connect(SshClient2.java:243)
	at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
	at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:386)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.io.IOException: Authentication failed
	at muon.app.ssh.SshClient2.connect(SshClient2.java:284)
	at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
	at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:386)
	at java.base/java.lang.Thread.run(Thread.java:834)
Terminal wrapper disconnecting
```

**To Reproduce**
1. Create a private key with password
2. Try to use this key for  a new session

**Expected behavior**
A dialog pops up and is asking for the password for the private key.

**Screenshots**
na

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Muon SSH 2.1.0

**Comment by devlinx9** [comment]
I reproduced the error, in the next version it will be resolved
