### ISSUE TITLE
SSH in port 23 Session not connected

### ISSUE THREAD

**Issue by Runig006** [devlinx9/muon-ssh#85]
**Describe the bug**
I have 20 diferents ssh connections ported from snowflake. One of them is a ArchLinux with an ssh in the port 23, it run Gitlab so 22 is reserve for that.

It works in Snowflake and mostly in MuonSSH, the only thing that doesnt work is the terminal. The password is correct, if it was that nothing will work, i have tested it too. If i use SnowFlake or ssh directly it work without any problem

1. Got a server with ssh and archlinux in port 23
2. Configure Muon to connect to that machine
3. Open the session and go to terminal

 - OS: Manjaro KDE

`Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: The dialog is displayable.
        at java.desktop/java.awt.Dialog.setUndecorated(Dialog.java:1273)
        at muon.app.ssh.GraphicalInputBlocker.lambda$blockInput$0(GraphicalInputBlocker.java:36)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Trying to get allowed authentication methods...
List of allowed authentications: [publickey, password]
Trying auth method: publickey
java.lang.Exception: No suitable key providers
        at muon.app.ssh.SshClient2.authPublicKey(SshClient2.java:115)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:242)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
        at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
        at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:383)
        at java.base/java.lang.Thread.run(Thread.java:833)
Trying auth method: password
net.schmizz.sshj.connection.ConnectionException: Request failed
        at net.schmizz.sshj.connection.channel.AbstractChannel.gotResponse(AbstractChannel.java:405)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:192)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:515)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Terminal wrapper disconnecting
currentSession: muon.app.ui.components.session.terminal.CustomJediterm[,0,0,1280x668,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@350a78e7,flags=9,maximumSize=,minimumSize=,preferredSize=]

     

RAW Paste Data
Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: The dialog is displayable.
        at java.desktop/java.awt.Dialog.setUndecorated(Dialog.java:1273)
        at muon.app.ssh.GraphicalInputBlocker.lambda$blockInput$0(GraphicalInputBlocker.java:36)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Trying to get allowed authentication methods...
List of allowed authentications: [publickey, password]
Trying auth method: publickey
java.lang.Exception: No suitable key providers
        at muon.app.ssh.SshClient2.authPublicKey(SshClient2.java:115)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:242)
        at muon.app.ssh.SshClient2.connect(SshClient2.java:167)
        at muon.app.ui.components.session.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:54)
        at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:383)
        at java.base/java.lang.Thread.run(Thread.java:833)
Trying auth method: password
net.schmizz.sshj.connection.ConnectionException: Request failed
        at net.schmizz.sshj.connection.channel.AbstractChannel.gotResponse(AbstractChannel.java:405)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:192)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:515)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Terminal wrapper disconnecting
currentSession: muon.app.ui.components.session.terminal.CustomJediterm[,0,0,1280x668,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@350a78e7,flags=9,maximumSize=,minimumSize=,preferredSize=]
[Public Pastes](https://pastebin.com/archive)

    [Paste Ping](https://pastebin.com/zt4Kkxh4)
    C | 20 min ago | 0.02 KB
    [Untitled](https://pastebin.com/dEwkzUPj)
    HTML | 27 min ago | 0.03 KB
    [Untitled](https://pastebin.com/CwfwNYND)
    Lua | 34 min ago | 1.14 KB
    [Untitled](https://pastebin.com/ZSdj3aRd)
    C | 37 min ago | 2.52 KB
    [start-end.cfg](https://pastebin.com/jG7n4Edp)
    YAML | 1 hour ago | 2.93 KB
    [Botania Turtle Wool Dropper](https://pastebin.com/qHHwB8s2)
    Lua | 1 hour ago | 1.24 KB
    [devmenu.js](https://pastebin.com/uh1cugya)
    JavaScript | 2 hours ago | 0.33 KB
    [imageprovider.cpp](https://pastebin.com/Qtuf9uiP)
    C++ | 2 hours ago | 1.19 KB`

**Comment by maddin79** [comment]
Hello @Runig006, 

I had the same problem and there is a bug in the Manjaro build. I guess it has something to do with the used java version in the Manjaro package. I downloaded the plain jar and run it with java -jar ... . Runs normally with that. 

Best
Martin

**Comment by Runig006** [comment]
True, for a temporal soluction is not a bad idea. I just put the jar in the desktop and added the icon. If someone can fix it in the one in the snap it will be perfect.

**Comment by devlinx9** [comment]
Hello, what Manjaro version do you have?

**Comment by devlinx9** [comment]
I'm going to close this issue, if the error persist with the new version 3.0.0 please let me know
